### ISSUE TITLE
Support with NextJS: navigator is not defined on "npm run build" Nextjs

### ISSUE THREAD

**Issue by collinli2353** [1000ship/react-scroll-motion#8]
First of all, this is a great module for scrolling motion. I am currently trying to build a personal website with this took to make my pages look more dynamic.

I am trying to use react-scroll-motion with next js but it seems to be an issue specifically with next.js not being able to access navigator and window since next.js renders react stuff on the server side. Online sources indicate the solution to fix this is to [dynamically import](https://nextjs.org/docs/advanced-features/dynamic-import).

I was not sure how to dynamically import react-scroll-motion since all the online references were importing a local component. Thus my solution was to import a component that used react-scroll-motion and loaded that component without server-side.
`const RSM = dynamic(
  () => import('./AboutMeDynamic.js'),
  { ssr: false, loading: ()=> <p>loading...</p> },
)`

This solution worked for "npm run dev" but when I try to deploy it on vercel (or just run "npm run build") the original navigator error pops up. Thus I am not sure why npm run dev works but npm run build does not. My code is on replit so you can run it and view it online: https://replit.com/@collinli2022/WonderfulBisqueLegacysystem. 

The error is shown below:
`ReferenceError: navigator is not defined
    at Object.<anonymous> (/home/runner/WonderfulBisqueLegacysystem/node_modules/react-scroll-motion/dist/utils/environment.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)`

**Comment by collinli2353** [comment]
I have solved this issue. My original idea of importing a component that used react-scroll-motion and loaded that component without server-side worked. However, one crucial thing I missed was that my component was in the pages directory. **Instead, it is absolutely crucial that component is in a different folder.**
